site_name: MkDocs Jinks Themes
site_url: http://yourname.net/
site_description: hello world its my new doc
site_author: yourname

repo_url: https://github.com/anetwork/mkdocs-jinks

copyright: Copyright &copy; 2017 yoursite

theme: jinks_fa
